languageCode = 'pl-pl'
paginate = 9
theme = "coHub"
title = 'Hackerspace Trójmiasto'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "O nas"
  url= "/o-nas"
  weight = 1
  [[menu.Main]]
  name = "Wydarzenia"
  url= "/wydarzenia"
  weight = 1
  [[menu.Main]]
  name = "Projekty"
  url= "/projekty"
  weight = 3
  [[menu.Main]]
  name = "Blog"
  url= "/blog"
  weight = 4
  [[menu.Main]]
  name = "Członkostwo"
  url= "/zasoby/czlonkostwo"
  weight = 5
  [[menu.Main]]
  name = "Zasoby"
  url= "/zasoby"
  weight = 6
  [[menu.Main]]
  name = "FAQ"
  url= "/#faq"
  weight = 7
  [[menu.Main]]
  name = "Kontakt"
  url= "/#contact"
  weight = 8

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "/contact"
  copyright = "© {year} Hackerspace Trójmiasto"
  googleAnalytics = ""
  logo = "/images/logo.png"
  footerlogo = "/images/logo.png"
  footerDescription = "Przyjdź i zbuduj coś z nami"

  [params.address]
  address = "al. Wojska Polskiego 41<br>80-268 Gdańsk"
  email = "kontakt@hs3.pl"
  openingDesc = "Otwarte całą dobę dla osób z kluczem."
  openingHours = "Jeśli nie masz klucza [zapytaj na Discord](https://hs3.pl/join) czy ktoś jest w środku."
  phone = "+48 661 691 133"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "54.3896193"
  longitude = "18.58178"
  pinImage = "/images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/hackerspacetrojmiasto"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/hs3city"
  weight = 2
  [[params.social]]
  icon = "ti-linkedin"
  url = "https://www.linkedin.com/company/hackerspace-tr%C3%B3jmiasto/"
  weight = 2
  [[params.social]]
  icon = "ti-user"
  url = "https://hs3.pl/join"
  weight = 3
  [[params.social]]
  icon = "ti-youtube"
  url = "https://www.youtube.com/channel/UC1MjdZvgtGZwSAaveL-Z8CA"
  weight = 4
  [[params.social]]
  icon = "ti-video-camera"
  url = "https://www.twitch.tv/hs3city"
  weight = 5  
  [[params.social]]
  icon = "ti-github"
  url = "https://github.com/hs3city"
  weight = 6
  [[params.social]]
  icon = "ti-wallet"
  url = "https://patronite.pl/hs3/description"
  weight = 7