name: "Fetch calendar events"

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Prerender calendar
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run Prerender
        run: |
          REPO=$PWD
          cd /tmp
          git clone -q https://github.com/DoomHammer/event-monitor.git emon
          cd $_
          git checkout prerendering
          ./build.sh
          mv build/index.html ${REPO}/calendar/
          cd $REPO
          git add calendar

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated calendar snapshot
